version: '3.5'
services:
  server:
    container_name: read_subtitles_from_image
    image: bigiskander/read_subtitles_from_image:1.1.0
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - "127.0.0.1:8080:8080"