version: '3.5'
services:
  photoprism:
    container_name: read_subtitles_from_image
    image: read_subtitles_from_image:latest
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - "127.0.0.1:8080:8080"